project:
  type: book
  output-dir: _book

book:
  title: "Ancient Pacific cod Genomics"
  author: "Sara M Schaal"
  date: last-modified 
  chapters:
    - index.qmd
    - 01-PCAs.qmd

bibliography: [references.bib]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


